### ISSUE TITLE
i2cScan in PCA9956

### ISSUE THREAD

**Issue by rbeekhuijzen** [yuskegoto/PCA9956#1]
Hello yuskegoto,

I'm trying to use the i2cScan in your code.
I can get the LEDs to work, so no problem there. 
But I would like to use the I2CScan to see the addresses of the chips in the chain. 
There are two PCA9956B board in the chain, one at 0x3F and one at 0x41
The code I'm using is:
<SNIP>
void loop()
  for (uint8_t BOARDx = 0; BOARDx < NUMBER_OF_BOARDS; BOARDx++)
  {
    Serial.println(ledDrivers[BOARDx].i2cScan());
    Serial.println(BOARDx, HEX);
    delay(50);
  }
...
<SNIP>

The serial monitor shows me the following (it keeps repeating):
...
I2C device found at address 0x3F
63
0

I2C device found at address 0x3F
63
1
...
<SNIP>

So the 0 and 1 are the board in the array (DP_PCA9956B ledDrivers[5]{{&Wire}, {&Wire}, {&Wire}, {&Wire}, {&Wire} };)
The 63is the decimal value of 0x3F.

But it does not detect the other address because of the break in I2CScan member.
Why is the break there? It only allows for the first address to be detected.

Other question:
When running on a UNO,, the code works as expected when I remove the break from your I2CScan.
But when I run the code on an Mega 2560 it does not.
Any ideas?

**Comment by yuskegoto** [comment]
Hi rbeekhuijzen!

The reason to place break in the scan loop is to return the found i2c address. If you want to continue the scan, you could comment out the break line, or continue the scan by observing return value from the function like this:
(Caution! I haven't tested the following code.)

```
for (uint8_t BOARDx = 0; BOARDx < NUMBER_OF_BOARDS; BOARDx++)
{
  uint8_t addr = 0;
  do
  {
    addr = ledDrivers[BOARDx].i2cScan(addr);
    if(addr != 0)
    {
      Serial.println(addr);
      Serial.println(BOARDx, HEX);
      addr++;
      delay(50);
    }
  }
  while(addr != 0);
}
```

> Other question:
When running on a UNO,, the code works as expected when I remove the break from your I2CScan.
But when I run the code on an Mega 2560 it does not.
Any ideas?

No idea. I haven't tested the code on Mega. How does it behave on Mega? Can you still control the PCA9956 from Mega without? if i2c communication works, you could maybe observe the error value returned from wire->endTransmission().

Hope this information helps!

**Comment by rbeekhuijzen** [comment]
Thanks for your reply!!
I'll let you know if (and when) I get it to work on a Mega 2560.
I think it should work, but perhaps the Mega 2560 (chinese version) I have
is defect or not 100% compatible. A original Mega is on the way.
Thanks again!!

Robert

**Comment by yuskegoto** [comment]
I'll close this issue since this is not directly related to core function of this driver.
